Repository GaePpaDev/GaePpa-BackEnd-DEV, pull requests merged in 2024-11, with the labels that each got.

#2 Update .gitignore
  .gitignore
Labels: documentation

#9 Feat: ApiResponseUtil 클래스 개발 #5
  src/main/java/com/sparta/ggaeppa/global/util/ApiResponseUtil.java
Labels: Enhancement

#12 전역 예외처리 핸들러 개발 #4
  build.gradle
  src/main/java/com/sparta/ggaeppa/global/exception/ControllerException.java
  src/main/java/com/sparta/ggaeppa/global/exception/DefaultException.java
  src/main/java/com/sparta/ggaeppa/global/exception/ExceptionStatus.java
  src/main/java/com/sparta/ggaeppa/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/ggaeppa/global/exception/RepositoryException.java
  src/main/java/com/sparta/ggaeppa/global/exception/ServiceException.java
  src/main/java/com/sparta/ggaeppa/global/util/ApiResponseUtil.java
Labels: Enhancement

#17 Feat#16 BaseEntity 개발
  src/main/java/com/sparta/gaeppa/global/base/AuditorAwareImpl.java
  src/main/java/com/sparta/gaeppa/global/base/BaseEntity.java
Labels: Enhancement

#21 Fix: optionPrice type 수정 #7
  src/main/java/com/sparta/gaeppa/cart/entity/Address.java
  src/main/java/com/sparta/gaeppa/cart/entity/Images.java
  src/main/java/com/sparta/gaeppa/cart/entity/OrderOptions.java
  src/main/java/com/sparta/gaeppa/cart/entity/OrderProducts.java
  src/main/java/com/sparta/gaeppa/cart/entity/Orders.java
  src/main/java/com/sparta/gaeppa/cart/entity/Payments.java
  src/main/java/com/sparta/gaeppa/cart/entity/Reviews.java
  src/main/resources/application.yml
  src/test/java/com/sparta/gaeppa/GaePpaApplicationTests.java
Labels: Enhancement

#23 Fix: 일부 어노테이션 사용법 수정 #22
  src/main/java/com/sparta/gaeppa/profile/entity/Profile.java
  src/main/java/com/sparta/gaeppa/security/config/CustomAuthenticationConfig.java
  src/main/java/com/sparta/gaeppa/store/entity/Store.java
Labels: Bug

#24 Feat: ProductCategory, Product, ProductOptionCategory, ProductOption CRUD 개발 #18
  src/main/java/com/sparta/gaeppa/global/base/AuditorAwareImpl.java
  src/main/java/com/sparta/gaeppa/global/exception/ExceptionStatus.java
  src/main/java/com/sparta/gaeppa/product/controller/ProductCategoryController.java
  src/main/java/com/sparta/gaeppa/product/controller/ProductController.java
  src/main/java/com/sparta/gaeppa/product/controller/ProductOptionCategoryController.java
  src/main/java/com/sparta/gaeppa/product/controller/ProductOptionController.java
  src/main/java/com/sparta/gaeppa/product/controller/ProductPicturesController.java
  src/main/java/com/sparta/gaeppa/product/dto/ProductResponseDto.java
  src/main/java/com/sparta/gaeppa/product/dto/StoreProductsResponseDto.java
  src/main/java/com/sparta/gaeppa/product/dto/product/ProductRequestDto.java
  src/main/java/com/sparta/gaeppa/product/dto/product/ProductResponseDto.java
  src/main/java/com/sparta/gaeppa/product/dto/product/StoreProductListResponseDto.java
  src/main/java/com/sparta/gaeppa/product/dto/productCategory/ProductCategoryRequestDto.java
  src/main/java/com/sparta/gaeppa/product/dto/productCategory/ProductCategoryResponseDto.java
  src/main/java/com/sparta/gaeppa/product/dto/productOption/ProductOptionListResponseDto.java
  src/main/java/com/sparta/gaeppa/product/dto/productOption/ProductOptionRequestDto.java
  src/main/java/com/sparta/gaeppa/product/dto/productOption/ProductOptionResponseDto.java
  src/main/java/com/sparta/gaeppa/product/dto/productOptionCategory/ProductOptionCategoryPutRequestDto.java
  src/main/java/com/sparta/gaeppa/product/dto/productOptionCategory/ProductOptionCategoryRequestDto.java
  src/main/java/com/sparta/gaeppa/product/dto/productOptionCategory/ProductOptionCategoryResponseDto.java
  src/main/java/com/sparta/gaeppa/product/entity/Product.java
  src/main/java/com/sparta/gaeppa/product/entity/ProductCategory.java
  src/main/java/com/sparta/gaeppa/product/entity/ProductOption.java
  src/main/java/com/sparta/gaeppa/product/entity/ProductOptionCategory.java
  src/main/java/com/sparta/gaeppa/product/repository/ProductCategoryRepository.java
  src/main/java/com/sparta/gaeppa/product/repository/ProductOptionCategoryRepository.java
  src/main/java/com/sparta/gaeppa/product/repository/ProductOptionRepository.java
  src/main/java/com/sparta/gaeppa/product/repository/ProductRepository.java
  src/main/java/com/sparta/gaeppa/product/service/ProductCategoryService.java
  src/main/java/com/sparta/gaeppa/product/service/ProductOptionCategoryService.java
  src/main/java/com/sparta/gaeppa/product/service/ProductOptionService.java
  src/main/java/com/sparta/gaeppa/product/service/ProductService.java
  src/main/java/com/sparta/gaeppa/security/config/SecurityConfig.java
  src/main/java/com/sparta/gaeppa/store/entity/Store.java
  src/test/java/com/sparta/gaeppa/product/controller/ProductCategoryControllerTest.java
Labels: Enhancement

#26 Fix: Product 도메인 Entity 의 빌더생성자 범위 수정 및 /api 기본경로 설정
  src/main/java/com/sparta/gaeppa/product/entity/Product.java
  src/main/java/com/sparta/gaeppa/product/entity/ProductCategory.java
  src/main/java/com/sparta/gaeppa/product/entity/ProductOption.java
  src/main/java/com/sparta/gaeppa/product/entity/ProductOptionCategory.java
  src/main/resources/application.yml
Labels: Enhancement

#27 Feat: Product 도메인의 Service Layer 단의 unit test 작성 #25
  src/main/java/com/sparta/gaeppa/product/dto/product/ProductRequestDto.java
  src/main/java/com/sparta/gaeppa/product/dto/product/StoreProductListResponseDto.java
  src/main/java/com/sparta/gaeppa/product/dto/productCategory/ProductCategoryRequestDto.java
  src/main/java/com/sparta/gaeppa/product/dto/productOption/ProductOptionListResponseDto.java
  src/main/java/com/sparta/gaeppa/product/dto/productOption/ProductOptionRequestDto.java
  src/main/java/com/sparta/gaeppa/product/dto/productOptionCategory/ProductOptionCategoryPutRequestDto.java
  src/main/java/com/sparta/gaeppa/product/dto/productOptionCategory/ProductOptionCategoryRequestDto.java
  src/main/java/com/sparta/gaeppa/product/entity/ProductCategory.java
  src/main/java/com/sparta/gaeppa/product/entity/ProductOptionCategory.java
  src/main/java/com/sparta/gaeppa/product/repository/ProductRepository.java
  src/main/java/com/sparta/gaeppa/product/service/ProductOptionCategoryService.java
  src/main/java/com/sparta/gaeppa/product/service/ProductService.java
  src/test/java/com/sparta/gaeppa/product/controller/ProductCategoryControllerTest.java
  src/test/java/com/sparta/gaeppa/product/service/ProductCategoryServiceTest.java
  src/test/java/com/sparta/gaeppa/product/service/ProductOptionCategoryServiceTest.java
  src/test/java/com/sparta/gaeppa/product/service/ProductOptionServiceTest.java
  src/test/java/com/sparta/gaeppa/product/service/ProductServiceTest.java
Labels: Test

#28 Feat : Order Entity 연관 관계 수정 및 Order 조회(GET) API 추가 #7
  src/main/java/com/sparta/gaeppa/global/exception/ExceptionStatus.java
  src/main/java/com/sparta/gaeppa/order/controller/OrderController.java
  src/main/java/com/sparta/gaeppa/order/dto/AddressDto.java
  src/main/java/com/sparta/gaeppa/order/dto/OrderProductDto.java
  src/main/java/com/sparta/gaeppa/order/dto/OrderProductOptionListDto.java
  src/main/java/com/sparta/gaeppa/order/dto/OrderResponseDto.java
  src/main/java/com/sparta/gaeppa/order/dto/OrderResponseListDto.java
  src/main/java/com/sparta/gaeppa/order/entity/Address.java
  src/main/java/com/sparta/gaeppa/order/entity/Images.java
  src/main/java/com/sparta/gaeppa/order/entity/OrderOptions.java
  src/main/java/com/sparta/gaeppa/order/entity/OrderProducts.java
  src/main/java/com/sparta/gaeppa/order/entity/Orders.java
  src/main/java/com/sparta/gaeppa/order/repository/OrderRepository.java
  src/main/java/com/sparta/gaeppa/order/service/OrderService.java
  src/main/java/com/sparta/gaeppa/payment/entity/Payments.java
  src/main/java/com/sparta/gaeppa/review/entity/Reviews.java
Labels: Enhancement

#35 Feat: AI를 이용한 유저의 상품 설명 추천 기능 #31
  src/main/java/com/sparta/gaeppa/ai/controller/AIController.java
  src/main/java/com/sparta/gaeppa/ai/dto/AssistProductDescriptionRequestDto.java
  src/main/java/com/sparta/gaeppa/ai/dto/AssistProductDescriptionResponseDto.java
  src/main/java/com/sparta/gaeppa/ai/dto/Gemini1_5ResponseDto.java
  src/main/java/com/sparta/gaeppa/ai/dto/Gemini1_5TextRequestDto.java
  src/main/java/com/sparta/gaeppa/ai/dto/SystemPromptRequestDto.java
  src/main/java/com/sparta/gaeppa/ai/dto/SystemPromptResponseDto.java
  src/main/java/com/sparta/gaeppa/ai/entity/AIInteractionLog.java
  src/main/java/com/sparta/gaeppa/ai/entity/AIPrompt.java
  src/main/java/com/sparta/gaeppa/ai/model/AIModelFactory.java
  src/main/java/com/sparta/gaeppa/ai/model/Gemini1_5Model.java
  src/main/java/com/sparta/gaeppa/ai/model/IAIModel.java
  src/main/java/com/sparta/gaeppa/ai/repository/AIInteractionLogRepository.java
  src/main/java/com/sparta/gaeppa/ai/repository/AIPromptRepository.java
  src/main/java/com/sparta/gaeppa/ai/service/AIService.java
  src/main/java/com/sparta/gaeppa/global/config/RestTemplateConfig.java
  src/main/java/com/sparta/gaeppa/global/exception/AIException.java
  src/main/java/com/sparta/gaeppa/global/exception/ExceptionStatus.java
  src/main/java/com/sparta/gaeppa/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/gaeppa/product/service/ProductCategoryService.java
  src/main/resources/application.yml
Labels: Enhancement

#41 Feat: 이미지 저장 로직 및 API 개발 #36 #43
  src/main/java/com/sparta/gaeppa/GaePpaApplication.java
  src/main/java/com/sparta/gaeppa/global/base/BaseEntity.java
  src/main/java/com/sparta/gaeppa/global/exception/ExceptionStatus.java
  src/main/java/com/sparta/gaeppa/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/gaeppa/global/exception/StorageException.java
  src/main/java/com/sparta/gaeppa/global/storage/FileSystemStorageService.java
  src/main/java/com/sparta/gaeppa/global/storage/StorageProperties.java
  src/main/java/com/sparta/gaeppa/global/storage/StorageService.java
  src/main/java/com/sparta/gaeppa/image/controller/ImageController.java
  src/main/java/com/sparta/gaeppa/image/dto/ImageResponseDto.java
  src/main/java/com/sparta/gaeppa/image/dto/ResourceDto.java
  src/main/java/com/sparta/gaeppa/image/entity/ProductImage.java
  src/main/java/com/sparta/gaeppa/image/entity/ReviewImage.java
  src/main/java/com/sparta/gaeppa/image/mime/MimeType.java
  src/main/java/com/sparta/gaeppa/image/repository/ProductImageRepository.java
  src/main/java/com/sparta/gaeppa/image/repository/ReviewImageRepository.java
  src/main/java/com/sparta/gaeppa/image/service/ProductImageService.java
  src/main/java/com/sparta/gaeppa/image/service/ReviewImageService.java
  src/main/java/com/sparta/gaeppa/product/entity/ProductPicture.java
  src/main/java/com/sparta/gaeppa/product/repository/ProductPictureRepository.java
  src/main/java/com/sparta/gaeppa/review/entity/Review.java
  src/main/java/com/sparta/gaeppa/review/repository/ReviewRepository.java
  src/main/resources/application-storage.yml
  src/main/resources/application.yml
Labels: Enhancement

#42 Feat : Payments GET,POST,PATCH 추가 #40
  build.gradle
  src/main/java/com/sparta/gaeppa/global/exception/ExceptionStatus.java
  src/main/java/com/sparta/gaeppa/order/controller/OrderController.java
  src/main/java/com/sparta/gaeppa/order/dto/OrderProductDto.java
  src/main/java/com/sparta/gaeppa/order/dto/OrderProductListDto.java
  src/main/java/com/sparta/gaeppa/order/dto/OrderProductOptionDto.java
  src/main/java/com/sparta/gaeppa/order/dto/OrderRequestDto.java
  src/main/java/com/sparta/gaeppa/order/dto/OrderResponseDto.java
  src/main/java/com/sparta/gaeppa/order/entity/OrderProduct.java
  src/main/java/com/sparta/gaeppa/order/entity/Orders.java
  src/main/java/com/sparta/gaeppa/order/service/OrderService.java
  src/main/java/com/sparta/gaeppa/payment/controller/PaymentController.java
  src/main/java/com/sparta/gaeppa/payment/dto/PaymentDto.java
  src/main/java/com/sparta/gaeppa/payment/entity/Payments.java
  src/main/java/com/sparta/gaeppa/payment/repository/PaymentsRepository.java
  src/main/java/com/sparta/gaeppa/payment/service/PaymentsService.java
  src/test/java/com/sparta/gaeppa/order/OrderTest.http
  src/test/java/com/sparta/gaeppa/payment/PaymentTest.http
Labels: Enhancement

#54 Fix: 하드삭제 로직 소프트 삭제로 변경
  build.gradle
  src/main/java/com/sparta/gaeppa/global/config/QuerydslConfig.java
  src/main/java/com/sparta/gaeppa/global/exception/ExceptionStatus.java
  src/main/java/com/sparta/gaeppa/product/controller/ProductCategoryController.java
  src/main/java/com/sparta/gaeppa/product/controller/ProductController.java
  src/main/java/com/sparta/gaeppa/product/controller/ProductOptionCategoryController.java
  src/main/java/com/sparta/gaeppa/product/controller/ProductOptionController.java
  src/main/java/com/sparta/gaeppa/product/controller/ProductPicturesController.java
  src/main/java/com/sparta/gaeppa/product/entity/Product.java
  src/main/java/com/sparta/gaeppa/product/entity/ProductCategory.java
  src/main/java/com/sparta/gaeppa/product/repository/ProductRepository.java
  src/main/java/com/sparta/gaeppa/product/repository/ProductRepositoryCustom.java
  src/main/java/com/sparta/gaeppa/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/com/sparta/gaeppa/product/service/ProductCategoryService.java
  src/main/java/com/sparta/gaeppa/product/service/ProductOptionCategoryService.java
  src/main/java/com/sparta/gaeppa/product/service/ProductOptionService.java
  src/main/java/com/sparta/gaeppa/product/service/ProductService.java
  src/main/java/com/sparta/gaeppa/security/jwts/service/RefreshService.java
  src/test/java/com/sparta/gaeppa/product/controller/ProductCategoryControllerTest.java
  src/test/java/com/sparta/gaeppa/product/service/ProductCategoryServiceTest.java
  src/test/java/com/sparta/gaeppa/product/service/ProductOptionCategoryServiceTest.java
  src/test/java/com/sparta/gaeppa/product/service/ProductOptionServiceTest.java
  src/test/java/com/sparta/gaeppa/product/service/ProductServiceTest.java
Labels: Enhancement

#58 Feat: Product 도메인 인가로직 개발 #55
  src/main/java/com/sparta/gaeppa/product/controller/ProductCategoryController.java
  src/main/java/com/sparta/gaeppa/product/controller/ProductController.java
  src/main/java/com/sparta/gaeppa/product/controller/ProductOptionCategoryController.java
  src/main/java/com/sparta/gaeppa/product/service/ProductCategoryService.java
  src/main/java/com/sparta/gaeppa/product/service/ProductOptionCategoryService.java
  src/main/java/com/sparta/gaeppa/product/service/ProductService.java
  src/main/java/com/sparta/gaeppa/security/config/SecurityConfig.java
  src/main/java/com/sparta/gaeppa/store/repository/StoreRepository.java
  src/test/java/com/sparta/gaeppa/GaePpaApplicationTests.java
  src/test/java/com/sparta/gaeppa/product/controller/ProductCategoryControllerTest.java
  src/test/java/com/sparta/gaeppa/product/service/ProductCategoryServiceTest.java
Labels: Enhancement

#61 Feat : Review CRUD 추가 및 Order<->Store 연결 완료 #53 #52
  src/main/java/com/sparta/gaeppa/global/exception/ExceptionStatus.java
  src/main/java/com/sparta/gaeppa/order/dto/OrderRequestDto.java
  src/main/java/com/sparta/gaeppa/order/dto/OrderResponseDto.java
  src/main/java/com/sparta/gaeppa/order/entity/Orders.java
  src/main/java/com/sparta/gaeppa/order/service/OrderService.java
  src/main/java/com/sparta/gaeppa/review/controller/ReviewController.java
  src/main/java/com/sparta/gaeppa/review/dto/ReviewRequestDto.java
  src/main/java/com/sparta/gaeppa/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/gaeppa/review/entity/Review.java
  src/main/java/com/sparta/gaeppa/review/repository/ReviewRepository.java
  src/main/java/com/sparta/gaeppa/review/service/ReviewService.java
  src/main/java/com/sparta/gaeppa/store/entity/Store.java
  src/test/java/com/sparta/gaeppa/review/ReviewTest.http
Labels: Enhancement

#71 Fix: 로그인 필터의 예외처리를 try catch로 수정
  src/main/java/com/sparta/gaeppa/ai/controller/AIController.java
  src/main/java/com/sparta/gaeppa/security/authentication/filters/LoginFilter.java
Labels: Bug

#73 Fix : 리뷰 평점 계산 반올림 삭제, 리뷰 삭제 요청시 본인 권한 확인 로직 추가
  src/main/java/com/sparta/gaeppa/review/repository/ReviewRepository.java
  src/main/java/com/sparta/gaeppa/review/service/ReviewService.java
  src/main/java/com/sparta/gaeppa/store/entity/Store.java
Labels: Enhancement
